image: "hub.ricebook.net/base/alpine:python-2016.09.27"
before_script:
    - "pip install pyinstaller"
    - "pip install -e git+http://gitlab.ricebook.net/platform/citadel-py.git#egg=citadelpy"

build_binary:
    stage: "test"
    script:
        - "ln -s /lib/libc.musl-x86_64.so.1 /usr/lib/libc.musl-x86_64.so.1"
        - "ln -s /lib/libz.so.1 /usr/lib/libz.so.1"
        - "python setup.py install"
        - "pyinstaller corecli.spec"
    artifacts:
        paths:
            - "dist/corecli"
        expire_in: "1 week"
